services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: frontend-${COMPOSE_PROJECT_NAME}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ~/.ii_agent/workspace:/app/data/workspace
    environment:
      - NODE_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: backend-${COMPOSE_PROJECT_NAME}
    init: true # Needed for the browser use
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      #Path of mounted file in docker
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-application-credentials.json
    volumes:
      #If file doesn't exist, use a dummy file
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./docker/.dummy-credentials.json}:/app/google-application-credentials.json
      - ~/.ii_agent:/.ii_agent
